services:
  backend:
    image: sparc-backend:latest
    container_name: django-backend
    ports:
      - "0.0.0.0:8000:8000"
    #volumes:
    #  - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  frontend:
    image: sparc-frontend:latest
    container_name: nuxt-frontend
    ports:
      - "0.0.0.0:3000:3000"
    #volumes:
    #  - ./frontend:/app
    #  - /app/node_modules
    environment:
      - NUXT_PUBLIC_API_BASE=http://192.168.178.59:8000
    depends_on:
      - backend

  db:
    image: postgres:18
    container_name: postgres-db
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    volumes:
      - pgdata:/var/lib/postgresql/18/data

volumes:
  pgdata: