# Generated by Django 5.2.8 on 2025-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disruption_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('ressource', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.IntegerField()),
                ('target_amount', models.IntegerField()),
                ('bill_of_materials', models.FileField(blank=True, null=True, upload_to='bill_of_materials/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], default='middle', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not yet started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ressource_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
