# Generated by Django 5.2.8 on 2025-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
