# Generated by Django 5.2.8 on 2025-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disruptiontype_process_resource_resourcetype_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disruption',
            name='comment',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
