# Generated by Django 5.2.8 on 2026-01-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisruptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sparc_disruption_type',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('work_time', models.TimeField()),
                ('setup_time', models.TimeField()),
            ],
            options={
                'db_table': 'sparc_process',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sparc_resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sparc_resource_type',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sparc_worker',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.IntegerField()),
                ('bill_of_materials', models.FileField(blank=True, null=True, upload_to='bill_of_materials/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ManyToManyField(blank=True, to='app.process')),
            ],
            options={
                'db_table': 'sparc_order',
            },
        ),
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disruptiontype')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disruptions', to='app.resource')),
            ],
            options={
                'db_table': 'sparc_disruption',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resourcetype'),
        ),
        migrations.AddField(
            model_name='process',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='processes', to='app.worker'),
        ),
    ]
