# Generated by Django 5.2.8 on 2026-01-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='resource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.resource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_of_materials',
            field=models.FileField(blank=True, null=True, upload_to='orders/bom/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/'),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='setup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='work_time',
            field=models.TimeField(null=True),
        ),
    ]
