# Generated by Django 5.2.8 on 2026-02-11 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_process_name_process_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disruption',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.process'),
            preserve_default=False,
        ),
    ]
