# Generated by Django 5.2.8 on 2026-02-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disruption_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disruption',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='disruption',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='work_time',
        ),
        migrations.AddField(
            model_name='disruption',
            name='created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disruption',
            name='duration',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process_time_seconds',
            field=models.IntegerField(default=0, help_text='Process time in seconds'),
        ),
        migrations.AddField(
            model_name='process',
            name='setup_time_seconds',
            field=models.IntegerField(default=0, help_text='Setup time in seconds'),
        ),
        migrations.AddField(
            model_name='process',
            name='waiting_time_seconds',
            field=models.IntegerField(default=0, help_text='Waiting time in seconds'),
        ),
        migrations.AlterField(
            model_name='disruption',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.process'),
        ),
        migrations.AlterField(
            model_name='disruption',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disruptions', to='app.resource'),
        ),
        migrations.AlterField(
            model_name='disruption',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.disruptiontype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.IntegerField(),
        ),
    ]
