# Generated by Django 5.2.8 on 2026-02-11 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_disruption_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='process',
            new_name='processes',
        ),
        migrations.AlterField(
            model_name='disruption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resourcetype'),
        ),
    ]
