# Generated by Django 5.2.8 on 2026-02-12 03:29

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_process_order_processes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill_of_materials',
        ),
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.order_file_upload_path)),
                ('file_type', models.CharField(choices=[('bom', 'Bill of Materials'), ('general', 'General File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='app.order')),
            ],
            options={
                'db_table': 'sparc_order_file',
            },
        ),
    ]
