# Generated by Django 5.2.8 on 2026-02-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_bill_of_materials_remove_order_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disruption',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_time_seconds',
        ),
        migrations.RemoveField(
            model_name='process',
            name='setup_time_seconds',
        ),
        migrations.RemoveField(
            model_name='process',
            name='waiting_time_seconds',
        ),
        migrations.AddField(
            model_name='disruption',
            name='disruption_time',
            field=models.IntegerField(default=0, help_text='Disruption time in seconds'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0, help_text='Order identifier with syntax: YYYYMMDDxzy'),
        ),
        migrations.AddField(
            model_name='process',
            name='approximated_time',
            field=models.IntegerField(default=0, help_text='The approximated time needed for one pice (in seconds)'),
        ),
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='setup_time',
            field=models.IntegerField(default=0, help_text='The time needed to set up the resource (in seconds)'),
        ),
        migrations.AddField(
            model_name='process',
            name='waiting_time',
            field=models.IntegerField(default=0, help_text='The time before you can access the resource as planed (in seconds)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_time', models.IntegerField(default=0, help_text='Process time in seconds')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process')),
            ],
            options={
                'db_table': 'sparc_part',
            },
        ),
    ]
