# Generated by Django 5.2.8 on 2026-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_disruption_duration_remove_order_processes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=255),
        ),
    ]
